# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GarbaseStatus',
            new_name='GarbageStatus',
        ),
    ]
